alltarget:r_server
r_server:server.cpp socket.cpp event.cpp rio.c http_helper.cpp multi_matrix.c url_encode.c
	g++ -std=c++11  -o r_server server.cpp socket.cpp event.cpp rio.c tool.cpp http_helper.cpp multi_matrix.c url_encode.c
clean:
	rm r_server
