#nc 127.0.0.1 port  
alltarget: simple_server simple_client
simple_server:simple_server.c
	gcc -o simple_server simple_server.c
simple_client:simple_client.c
	gcc -o simple_client simple_client.c
clean:
	rm  simple_server simple_client	
